import { ROUTES } from "@/constants/routes";
import type { Service } from "@/types/service";

export const SERVICE_SLUGS = [
  "handyman",
  "tv-wall-mounting",
  "furniture-assembly",
  "plumbers",
  "electricians",
  "move-in-move-out-repairs",
  "home-maintenance",
  "painters",
  "renovators",
  "flooring",
  "cleaners",
  "landscapers",
  "deck-fence",
] as const;

export type ServiceSlug = (typeof SERVICE_SLUGS)[number];

export const SERVICES: Service[] = [
  {
    slug: "handyman",
    name: "Handyman Services",
    pluralName: "Handymen",
    shortDescription: "Repairs, installs, drywall, doors, and general home fixes",
    icon: "wrench",
    href: ROUTES.seoLanding.handyman,
    featured: true,
    sortOrder: 1,
    cardCta: "Get a Free Handyman Quote",
    quoteCta: "Get a Free Handyman Quote",
  },
  {
    slug: "tv-wall-mounting",
    name: "TV Wall Mounting",
    pluralName: "TV Mounting Specialists",
    shortDescription: "Secure TV mounting with clean, concealed wiring",
    icon: "layers",
    href: ROUTES.seoLanding.tvWallMounting,
    featured: true,
    sortOrder: 2,
    cardCta: "Get a Free TV Wall Mounting Quote",
    quoteCta: "Get a Free TV Wall Mounting Quote",
  },
  {
    slug: "furniture-assembly",
    name: "Furniture Assembly",
    pluralName: "Furniture Assemblers",
    shortDescription: "IKEA, flat-pack, and custom furniture built right",
    icon: "clipboard-list",
    href: ROUTES.seoLanding.furnitureAssembly,
    featured: true,
    sortOrder: 3,
    cardCta: "Get a Free Furniture Assembly Quote",
    quoteCta: "Get a Free Furniture Assembly Quote",
  },
  {
    slug: "cleaners",
    name: "Cleaning Services",
    pluralName: "Cleaning Services",
    shortDescription:
      "Professional cleaning services for homes, apartments, condos, offices, rental properties, and post-construction projects throughout Edmonton and surrounding areas.",
    icon: "cleaning",
    href: ROUTES.services.detail("cleaners"),
    featured: true,
    sortOrder: 4,
    // highlights: [
    //   "New Home Cleaning",
    //   "Apartment & Condo Cleaning",
    //   "Move-In / Move-Out Cleaning",
    //   "Commercial & Office Cleaning",
    //   "Post-Construction Cleaning",
    //   "Rental Property Cleaning",
    // ],
    cardCta: "Get a Free Cleaning Quote",
    quoteCta: "Get a Free Cleaning Quote",
  },
  {
    slug: "plumbers",
    name: "Plumbing Maintenance",
    pluralName: "Plumbers",
    shortDescription: "Leaks, taps, drains, toilets, and fixture repairs",
    icon: "droplets",
    href: ROUTES.services.detail("plumbers"),
    featured: true,
    sortOrder: 5,
    cardCta: "Get a Free Plumbing Maintenance Quote",
    quoteCta: "Get a Free Plumbing Maintenance Quote",
  },
  {
    slug: "electricians",
    name: "Electrical Maintenance",
    pluralName: "Electricians",
    shortDescription: "Outlets, switches, lighting, and minor electrical fixes",
    icon: "zap",
    href: ROUTES.services.detail("electricians"),
    featured: true,
    sortOrder: 6,
    cardCta: "Get a Free Electrical Maintenance Quote",
    quoteCta: "Get a Free Electrical Maintenance Quote",
  },
  {
    slug: "move-in-move-out-repairs",
    name: "Move-In / Move-Out Repairs",
    pluralName: "Move-In / Move-Out Specialists",
    shortDescription: "Patch holes, fix scuffs, and get rentals move-ready",
    icon: "home",
    href: ROUTES.seoLanding.moveInMoveOut,
    featured: true,
    sortOrder: 7,
    cardCta: "Get a Free Move-In / Move-Out Repairs Quote",
    quoteCta: "Get a Free Move-In / Move-Out Repairs Quote",
  },
  {
    slug: "home-maintenance",
    name: "House & Condo Maintenance",
    pluralName: "Home Maintenance Crew",
    shortDescription: "Seasonal upkeep and preventative care for homes and condos",
    icon: "shield-check",
    href: ROUTES.services.detail("home-maintenance"),
    featured: true,
    sortOrder: 8,
    cardCta: "Get a Free House & Condo Maintenance Quote",
    quoteCta: "Get a Free House & Condo Maintenance Quote",
  },
  {
    slug: "painters",
    name: "Painters",
    pluralName: "Painters",
    shortDescription: "Interior, exterior, and cabinet painting",
    icon: "paintbrush",
    href: ROUTES.services.detail("painters"),
    featured: false,
    sortOrder: 8,
    cardCta: "Get a Free Painters Quote",
    quoteCta: "Get a Free Painters Quote",
  },
  {
    slug: "renovators",
    name: "Renovators",
    pluralName: "Renovators",
    shortDescription: "Kitchen, bathroom, and basement renos",
    icon: "home",
    href: ROUTES.services.detail("renovators"),
    featured: false,
    sortOrder: 9,
    cardCta: "Get a Free Renovators Quote",
    quoteCta: "Get a Free Renovators Quote",
  },
  {
    slug: "flooring",
    name: "Flooring",
    pluralName: "Flooring Installers",
    shortDescription: "Hardwood, tile, laminate, and vinyl",
    icon: "layers",
    href: ROUTES.services.detail("flooring"),
    featured: false,
    sortOrder: 10,
    cardCta: "Get a Free Flooring Quote",
    quoteCta: "Get a Free Flooring Quote",
  },
  {
    slug: "landscapers",
    name: "Landscapers",
    pluralName: "Landscapers",
    shortDescription: "Lawns, gardens, and yard cleanup",
    icon: "tree",
    href: ROUTES.services.detail("landscapers"),
    featured: false,
    sortOrder: 12,
    cardCta: "Get a Free Landscapers Quote",
    quoteCta: "Get a Free Landscapers Quote",
  },
  {
    slug: "deck-fence",
    name: "Deck & Fence",
    pluralName: "Deck & Fence Specialists",
    shortDescription: "Builds, repairs, and staining",
    icon: "fence",
    href: ROUTES.services.detail("deck-fence"),
    featured: false,
    sortOrder: 13,
  },
];

export const SERVICE_BY_SLUG = Object.fromEntries(
  SERVICES.map((s) => [s.slug, s])
) as Record<ServiceSlug, Service>;

export const FEATURED_SERVICES = SERVICES.filter((s) => s.featured).sort(
  (a, b) => a.sortOrder - b.sortOrder
);
